# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

netAlign <- function(A, B, L, alpha = 1.0, beta = 1.0, gamma = 0.99, maxiter = 100L, finalize = FALSE) {
    .Call(`_netAlignR_netAlign`, A, B, L, alpha, beta, gamma, maxiter, finalize)
}

